### ISSUE TITLE
enzyme is not a binary

### ISSUE THREAD

**Issue by simonwuelker** [rust-ml/enzyme_build#7]
According to README.md, this should be built like this:
```
$ cargo install enzyme
$ enzyme-install
```
Executing `cargo install enzyme` fails however, since `enzyme` is a library, not a binary.
```
    Updating crates.io index
error: there is nothing to install in `enzyme v0.1.0`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency in a Cargo project instead.
```
I am using `cargo 1.58.0-nightly (40dc28175 2021-12-06)`

Running `cargo install --path <path to Cargo.toml>` works fine. Is the version on crates.io the correct one?

**Comment by ZuseZ4** [comment]
Indeed, crates.io only had the old Readme which someone used to reserve the name. 
I've prepared everything for the final release, but then decided to wait for the weekend and my new SSD, 
in order to test the build on a fresh Ubuntu, to see if I missed some dependencies (spoiler: I did). 
I've published it right now.
